#!/bin/bash

system_type=$(uname -s)

# Install composer if it's not installed.
if ! command -v composer >/dev/null 2>&1; then
  curl https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
fi

# macOS
if [ "$system_type" = "Darwin" ]; then

  if [ -d "${HOME}/.config/fonts/" ]; then
     cp -n ~/.config/fonts/*.ttf /Library/Fonts/
  fi

  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh
  fi

  for CMD in exa bat diff-so-fancy fish tldr prettyping ack jq httpie tmux
  do
    if ! brew list "${CMD}" >/dev/null 2>&1; then
      echo "Installing ${CMD}"
      brew install "${CMD}"
    fi
  done

  for CMD in lastpass aerial diffmerge discord flux grammarly iterm2 licecap macdown meld muzzle phpstorm skitch slack sourcetree rectangle spotify tableplus typora visual-studio-code vlc lando vagrant virtualbox
  do
    if ! brew cask list "${CMD}" >/dev/null 2>&1; then
      echo "Installing ${CMD}"
      brew cask install "${CMD}"
    fi
  done

  if ! command -v travis >/dev/null 2>&1; then
    echo "Installing Travis CLI."
    gem install travis --no-document --user-install
  fi

elif [ "$system_type" = "Linux" ]; then

  for CMD in tldr prettyping ack jq unzip php sqlite tmux
  do
    if ! command -v "${CMD}" >/dev/null 2>&1; then
      echo "Installing ${CMD}"
      sudo apt -y install "${CMD}"
    fi
  done

  if ! command -v http >/dev/null 2>&1; then
    echo "Installing httpie"
    sudo apt -y install httpie
  fi

  if ! command -v exa >/dev/null 2>&1; then
    echo "Installing Exa"
    sudo wget -O /tmp/exa-linux-x86_64-0.9.0.zip https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip &&
    unzip /tmp/exa-linux-x86_64-0.9.0.zip -d /usr/local/bin/ && \
    rm /tmp/exa-linux-x86_64-0.9.0.zip && \
    mv /usr/local/bin/exa-linux-x86_64 /usr/local/bin/exa && \
    chmod a+x /usr/local/bin/exa

    sudo wget -O /usr/local/man/exa.1 https://raw.githubusercontent.com/ogham/exa/master/contrib/man/exa.1

    sudo mkdir -p /usr/share/fish/
    sudo wget -O /usr/share/fish/completions.fish https://raw.githubusercontent.com/ogham/exa/master/contrib/completions.fish
  fi

  if ! command -v diff-so-fancy >/dev/null 2>&1; then
    echo "Installing Diff So Fancy"
    sudo wget -O /usr/local/bin/diff-so-fancy https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy && \
    chmod a+x /usr/local/bin/diff-so-fancy
  fi

  if ! command -v fish >/dev/null 2>&1; then
    echo "Installing Fish Shell"
    sudo apt-add-repository -y ppa:fish-shell/release-3 && \
    apt -y update && \
    apt -y install fish
  fi

  if ! command -v composer >/dev/null 2>&1; then
    wget https://getcomposer.org/installer -O - -q | php -- --quiet
    sudo mv composer.phar /usr/local/bin/composer && \
      chmod a+x,g+w /usr/local/bin/composer
  fi

  for PHP_PACKAGE in curl intl xml mbstring mysql xdebug sqlite3 gd zip
  do
    if ! php -m | grep -q "${PHP_PACKAGE}"; then
      sudo apt -y install "php-${PHP_PACKAGE}"
    fi
  done

fi

if command -v fish >/dev/null 2>&1 && [ `command -v fish` != "${SHELL}" ]; then
  echo "Setting Fish as default shell"
  grep -q `command -v fish` /etc/shells || command -v fish | sudo tee -a /etc/shells >/dev/null
  chsh -s `command -v fish`
fi

if command -v diff-so-fancy >/dev/null 2>&1; then
  git config --file ~/.gitconfig.local core.pager "diff-so-fancy | less --tabs=4 -RFX"
fi

for PACKAGE in "hirak/prestissimo" "squizlabs/php_codesniffer" "friendsofphp/php-cs-fixer" "ergebnis/composer-normalize" "dealerdirect/phpcodesniffer-composer-installer" "phpmd/phpmd" "laravel/installer"
do
  if ! composer global info "${PACKAGE}" >/dev/null 2>&1; then
    echo "Installing ${PACKAGE}"
    composer global require --dev "${PACKAGE}"
  fi
done

if ! command -v ads >/dev/null 2>&1; then
  curl https://downloads.acquia.studio/install-standalone.sh | bash
fi
