#!/usr/bin/env bash

COMPOSER_PACKAGES=("hirak/prestissimo" "squizlabs/php_codesniffer" "friendsofphp/php-cs-fixer" "ergebnis/composer-normalize" "dealerdirect/phpcodesniffer-composer-installer" "phpmd/phpmd" "laravel/installer")
VAGRANT_PLUGINS=("exec", "hostsupdater", "vbguest", "cachier")

system_type=$(uname -s)

# Install composer if it's not installed.
if ! command -v composer >/dev/null 2>&1; then
  curl https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
fi

for PACKAGE in $COMPOSER_PACKAGES; do
  if ! composer global info "${PACKAGE}" >/dev/null 2>&1; then
    echo "Installing ${PACKAGE}"
    composer global require --dev "${PACKAGE}"
  fi
done

source "$(dirname "$0")/bootstrap.${system_type}"

if command -v fish >/dev/null 2>&1 && [ `command -v fish` != "${SHELL}" ]; then
  echo "Setting Fish as default shell"
  grep -q `command -v fish` /etc/shells || command -v fish | sudo tee -a /etc/shells >/dev/null
  chsh -s `command -v fish`
fi

if command -v diff-so-fancy >/dev/null 2>&1; then
  git config --file ~/.gitconfig.local core.pager "diff-so-fancy | less --tabs=4 -RFX"
fi

if ! command -v ads >/dev/null 2>&1; then
  echo "Installing ads."
  curl https://downloads.acquia.studio/install-standalone.sh | bash
fi

if ! command -v drush >/dev/null 2>&1; then
  echo "Installing drush launcher."
  sudo wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar && \
  chmod a+x /usr/local/bin/drush
fi

if [ ! -d "${HOME}/.vim_runtime" ]; then
  echo "Installimg vimrc changes."
  git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
  sh ~/.vim_runtime/install_awesome_vimrc.sh
fi

if [ ! -f "${HOME}/.nvm/nvm.sh" ]; then
  echo "Installing nvm"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
fi

if command -v vagrant >/dev/null 2>&1; then
  for PLUGIN in $VAGRANT_PLUGINS; do
    if ! vagrant plugin list | grep "vagrant-${PLUGIN}"; then
      vagrant plugin install "vagrant-${PLUGIN}"
    fi
  done
fi

if ! command -v drush >/dev/null 2>&1; then
  echo "Installing drush launcher."
  sudo wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar && \
  chmod a+x /usr/local/bin/drush
fi