#!/usr/bin/env bash

COMPOSER_PACKAGES=("hirak/prestissimo" "squizlabs/php_codesniffer" "friendsofphp/php-cs-fixer" "ergebnis/composer-normalize" "dealerdirect/phpcodesniffer-composer-installer" "phpmd/phpmd" "laravel/installer")

system_type=$(uname -s)

# Install composer if it's not installed.
if ! command -v composer >/dev/null 2>&1; then
  curl https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
fi

for PACKAGE in $COMPOSER_PACKAGES; do
  if ! composer global info "${PACKAGE}" >/dev/null 2>&1; then
    echo "Installing ${PACKAGE}"
    composer global require --dev "${PACKAGE}"
  fi
done

source "$(dirname "$0")/bootstrap.${system_type}"

if command -v fish >/dev/null 2>&1 && [ `command -v fish` != "${SHELL}" ]; then
  echo "Setting Fish as default shell"
  grep -q `command -v fish` /etc/shells || command -v fish | sudo tee -a /etc/shells >/dev/null
  chsh -s `command -v fish`
fi

if command -v diff-so-fancy >/dev/null 2>&1; then
  git config --file ~/.gitconfig.local core.pager "diff-so-fancy | less --tabs=4 -RFX"
fi

if ! command -v ads >/dev/null 2>&1; then
  curl https://downloads.acquia.studio/install-standalone.sh | bash
fi
